apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firstapp
  namespace: argocd-test
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd-test
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: apps/firstapp
    repoURL: https://github.com/alangiacomin/myapp/
    targetRevision: master
    helm:
      releaseName: firstapp
      values: |
        nameOverride: "my new override"
