apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sapp
  namespace: argocd-test
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd-test
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: apps/k8sapp
    repoURL: https://github.com/alangiacomin/myapp/
    targetRevision: master
