apiVersion: apps/v1
kind: Deployment
metadata:
   name: k8s-app
   namespace: argocd-test
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: k8s-app
              image: alangiacomin/k8s-app:1707338912
---
apiVersion: v1
kind: Service
metadata:
   name: k8s-app-entrypoint
   namespace: argocd-test
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 8000
        targetPort: 8000
        nodePort: 30001
