apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    chart: mychart
    repoURL: https://github.com/alangiacomin/mychart
    targetRevision: 0.1.0
    helm:
      releaseName: myapp
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
