apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapps
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: mychart
    repoURL: https://github.com/alangiacomin/mychart
    targetRevision: 0.1.0
    helm:
      releaseName: myapp
      valueFiles:
        - values.yaml
