apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secondapp
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: apps/firstapp
    repoURL: https://github.com/alangiacomin/myapp/
    targetRevision: master
    helm:
      releaseName: secondapp
      values: |
        nameOverride: "my second override"
