apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-app-cm-env
  namespace: myapp-test
data:
  .env.cm: |
    APP_NAME="Ciao mondo 35"
    APP_URL=http://app.cobradev.net
    APP_ENV=local
    APP_DEBUG=true
    #DB_CONNECTION=sqlite
    DB_CONNECTION=mysql
    DB_HOST=localhost
    DB_PORT=3306
    DB_DATABASE=zdhhezcz_k8s
    DB_USERNAME=zdhhezcz_k8s_admin
    DB_PASSWORD=VMQ4baF*TGi^$ze4
