apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-app-cm-env
  namespace: argocd-test
data:
  .env.cm: |
    APP_NAME="Hello world 1"
    APP_URL=http://app1.cobradev.net
    APP_ENV=local
    APP_DEBUG=true
    
    DB_CONNECTION=sqlite
    #DB_CONNECTION=mysql
    #DB_HOST=46.252.150.71
    #DB_PORT=3306
    #DB_DATABASE=zdhhezcz_k8s
    #DB_USERNAME=zdhhezcz_k8s_admin
    #DB_PASSWORD=VMQ4baF*TGi^$ze4
    
    #SESSION_DRIVER=file
    SESSION_DRIVER=database
    
    #QUEUE_CONNECTION=redis
    #REDIS_CLIENT=predis
    #REDIS_HOST=redis-11687.c284.us-east1-2.gce.redns.redis-cloud.com
    #REDIS_PASSWORD=MfqlxoE3eLPFETiuByfN8Q6CpaYi9EGW
    #REDIS_PORT=11687
    
    NTS_TEST=false
    NTS_SERVER=false
    #NTS_HOST=46.252.150.71
    NTS_HOST=46.252.150.71
    NTS_PORT=80
    NTS_DATABASE=zdhhezcz_k8s
    NTS_USERNAME=zdhhezcz_k8s_admin
    NTS_PASSWORD=VMQ4baF*TGi^$ze4
    
    REVERB_HOST="app1.cobradev.net"
    
    #VITE_APP_NAME="${APP_NAME}"
    #VITE_APP_URL="${APP_URL}"
    
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: nts-database
#  namespace: myapp-test
#subsets:
#  - addresses:
#      - ip: 46.252.150.71
#    ports:
#      - port: 3306
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nts-database
#  namespace: myapp-test
#spec:
#  ports:
#    - port: 3306
#      targetPort: 3306
