apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-app-cm-env
  namespace: argocd-test
data:
  .env.cm: |
    APP_NAME="Hello world 1"
    APP_URL=http://app1.cobradev.net
    APP_ENV=local
    APP_DEBUG=true
    #DB_CONNECTION=sqlite
    DB_CONNECTION=mysql
    DB_HOST=46.252.150.71
    DB_PORT=3306
    DB_DATABASE=zdhhezcz_k8s
    DB_USERNAME=zdhhezcz_k8s_admin
    DB_PASSWORD=VMQ4baF*TGi^$ze4
    NTS_TEST=false
    NTS_SERVER=true
    #NTS_HOST=46.252.150.71
    NTS_HOST=46.252.150.71
    NTS_PORT=80
    NTS_DATABASE=zdhhezcz_k8s
    NTS_USERNAME=zdhhezcz_k8s_admin
    NTS_PASSWORD=VMQ4baF*TGi^$ze4
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: nts-database
#  namespace: myapp-test
#subsets:
#  - addresses:
#      - ip: 46.252.150.71
#    ports:
#      - port: 3306
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nts-database
#  namespace: myapp-test
#spec:
#  ports:
#    - port: 3306
#      targetPort: 3306
