apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: argocd-test
spec:
  clusterIP: None
  ports:
  - port: 3306


---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: argocd-test
subsets:
  - addresses:
        - ip: 46.252.150.71
    ports:
      - port: 3306
        name: mysql
