kind: "Service"
apiVersion: "v1"
metadata:
  name: "mysql"
  namespace: myapp-test
spec:
  ports:
    -
      name: "mysql"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
      nodePort: 0
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "mysql"
  namespace: myapp-test
subsets:
  -
    addresses:
      -
        ip: "46.252.150.71"
    ports:
      -
        port: 3306
        name: "mysql"
