apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  namespace: argocd-test
  annotations:
    configmap.reloader.stakater.com/reload: "k8s-app-cm-env"
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: k8s-app
          image: alangiacomin/k8s-app:1714597110
          volumeMounts:
            - name: k8s-app-configmap
              mountPath: /var/www/html/.env.cm
              subPath: .env.cm
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: k8s-app-configmap
          configMap:
            name: k8s-app-cm-env
