apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  namespace: argocd-test
  annotations:
    configmap.reloader.stakater.com/reload: "k8s-app-cm-env"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 1
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
        - name: k8s-app
          image: alangiacomin/k8s-app:1736713058
          tty: true
          volumeMounts:
            - name: k8s-app-configmap
              mountPath: /var/www/html/.env.cm
              subPath: .env.cm
              readOnly: true
          env:
            - name: DEPLOY_PURPOSE
              value: WEB
      terminationGracePeriodSeconds: 5
      volumes:
        - name: k8s-app-configmap
          configMap:
            name: k8s-app-cm-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-queue
  namespace: argocd-test
  annotations:
    configmap.reloader.stakater.com/reload: "k8s-app-cm-env"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 1
  selector:
    matchLabels:
      app: k8s-app-queue
  template:
    metadata:
      labels:
        app: k8s-app-queue
    spec:
      containers:
        - name: k8s-app-queue
          image: alangiacomin/k8s-app:1736713058
          volumeMounts:
            - name: k8s-app-queue-configmap
              mountPath: /var/www/html/.env.cm
              subPath: .env.cm
              readOnly: true
          env:
            - name: DEPLOY_PURPOSE
              value: QUEUE_DEFAULT
      terminationGracePeriodSeconds: 5
      volumes:
        - name: k8s-app-queue-configmap
          configMap:
            name: k8s-app-cm-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-notifications
  namespace: argocd-test
  annotations:
    configmap.reloader.stakater.com/reload: "k8s-app-cm-env"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 1
  selector:
    matchLabels:
      app: k8s-app-notifications
  template:
    metadata:
      labels:
        app: k8s-app-notifications
    spec:
      containers:
        - name: k8s-app-notifications
          image: alangiacomin/k8s-app:1736713058
          volumeMounts:
            - name: k8s-app-notifications-configmap
              mountPath: /var/www/html/.env.cm
              subPath: .env.cm
              readOnly: true
          env:
            - name: DEPLOY_PURPOSE
              value: QUEUE_NOTIFICATION
      terminationGracePeriodSeconds: 5
      volumes:
        - name: k8s-app-notifications-configmap
          configMap:
            name: k8s-app-cm-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-reverb
  namespace: argocd-test
  annotations:
    configmap.reloader.stakater.com/reload: "k8s-app-cm-env"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 1
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
        app2: k8s-app-reverb
    spec:
      containers:
        - name: k8s-app-reverb
          image: alangiacomin/k8s-app:1736713058
          volumeMounts:
            - name: k8s-app-reverb-configmap
              mountPath: /var/www/html/.env.cm
              subPath: .env.cm
              readOnly: true
          env:
            - name: DEPLOY_PURPOSE
              value: REVERB
          ports:
          - containerPort: 8119
            name: "8119-port"
      terminationGracePeriodSeconds: 5
      volumes:
        - name: k8s-app-reverb-configmap
          configMap:
            name: k8s-app-cm-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-pulse
  namespace: argocd-test
  annotations:
    configmap.reloader.stakater.com/reload: "k8s-app-cm-env"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 1
  selector:
    matchLabels:
      app: k8s-app-pulse
  template:
    metadata:
      labels:
        app: k8s-app-pulse
    spec:
      containers:
        - name: k8s-app-pulse
          image: alangiacomin/k8s-app:1736713058
          volumeMounts:
            - name: k8s-app-pulse-configmap
              mountPath: /var/www/html/.env.cm
              subPath: .env.cm
              readOnly: true
          env:
            - name: DEPLOY_PURPOSE
              value: PULSE
      terminationGracePeriodSeconds: 5
      volumes:
        - name: k8s-app-pulse-configmap
          configMap:
            name: k8s-app-cm-env
