---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  namespace: argocd-test
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: k8s-app
          image: alangiacomin/k8s-app:1714421837
          volumeMounts:
            - name: k8s-app-configmap
              mountPath: /var/www/html/
              subPath: .env.cm
              #readOnly: true
      volumes:
        - name: k8s-app-configmap
          configMap:
            name: k8s-app-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app-entrypoint
  namespace: argocd-test
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
    - port: 80
      targetPort: 8123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-app-configmap
  namespace: argocd-test
data:
  .env.production: |
    APP_NAME="Ciao mondo 2"
    APP_ENV=local
