apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  namespace: argocd-test
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: k8s-app
          image: alangiacomin/k8s-app:1714425219
          volumeMounts:
            - name: k8s-app-configmap
              mountPath: /var/www/html/.env.cm
              subPath: .env.cm
              readOnly: true
      volumes:
        - name: k8s-app-configmap
          configMap:
            name: k8s-app-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app-entrypoint
  namespace: argocd-test
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
    - port: 80
      targetPort: 8123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-app-configmap
  namespace: argocd-test
  annotations:    
    configmap-version: "2"
data:
  .env.cm: |
    APP_NAME:"Ciao mondo 21"
    APP_ENV:production
