apiVersion: v1
kind: Service
metadata:
  name: k8s-app-entrypoint
  namespace: argocd-test
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
    - port: 80
      name: web
      targetPort: 8123
      
