apiVersion: v1
kind: Service
metadata:
  name: k8s-app-loadbalancer
  namespace: argocd-test
spec:
  type: LoadBalancer
  selector:
    lbtype: external
  ports:
    - port: 80
      name: web
      targetPort: "8123-port"
    - port: 8119
      name: reverb
      targetPort: "8119-port"
      
