apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prometheus-kube-prome-prometheus
  namespace: argocd-test
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - backend:
          service:
            name: kustomize-guestbook-ui
            port:
              number: 8010
        path: /
        pathType: ImplementationSpecific
  - http:
      paths:
      - backend:
          service:
            name: kustomize-newsvc
            port:
              number: 8020
        path: /
        pathType: ImplementationSpecific
#  tls:
#  - hosts:
#    - guest.cobradev.net
