apiVersion: apps/v1
kind: Deployment
metadata:
   name: staticweb
   namespace: argocd-test
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: staticweb
              image: alangiacomin/web-image:0.0.1
---
apiVersion: v1
kind: Service
metadata:
   name: staticweb-entrypoint
   namespace: argocd-test
spec:
   # type: NodePort
   type: LoadBalancer
   selector:
      bb: web
   ports:
      - port: 8020
        targetPort: 8020
        nodePort: 30002
